# bryxcoin server configuration file

# the mongodb target to read from to fetch user addresses and secrets
mongo_connection_string = "mongodb+srv://adminuser:0sqj9fjfPNGTI9oa@erwijet-atlas.jn7aj5y.mongodb.net/bagelbot"
mongo_user_database = "bryxcoin"
mongo_user_collection = "users"

# the public and private key pair to authenticate to git with
public_key = "/Users/tyler/.ssh/id_ed25519.pub"
private_key = "/Users/tyler/.ssh/id_ed25519"

# the git repo to use as the bryxcoin ledger
ledger_repo = "git@github.com:bryxcoin/ledger.git"

# the port to serve the bryxcoin server on
port = "8080"